In [4]:
#importing the dependencies 
import numpy as np 
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [5]:
#importing different types of model
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [6]:
#loading the dataset
dataset=pd.read_csv('heart.csv')

In [7]:
dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [8]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
dataset['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [10]:
x=dataset.drop(columns='target',axis=1)
y=dataset.target

In [11]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [12]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [13]:
X=np.asarray(x)
Y=np.asarray(y)

### Model Selection

1.Compare the model with default hyperparameter value using cross validation

In [14]:
#list of models
models=[LogisticRegression(max_iter=1000),SVC(kernel='linear'), KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [15]:
def compare_model_cross_validation():
    for model in models:
        cv_score=cross_val_score(model,X,Y,cv=5)
        mean_accuracy=sum(cv_score)/len(cv_score)
        print(f"the cross validation score of {model} is ={cv_score}")
        print(f"the accuracy score of the {model} is:{mean_accuracy*100:.2f}%")
        print("-------------------------------------------------------------")

In [16]:
compare_model_cross_validation()

the cross validation score of LogisticRegression(max_iter=1000) is =[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
the accuracy score of the LogisticRegression(max_iter=1000) is:82.83%
-------------------------------------------------------------
the cross validation score of SVC(kernel='linear') is =[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
the accuracy score of the SVC(kernel='linear') is:82.83%
-------------------------------------------------------------
the cross validation score of KNeighborsClassifier() is =[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
the accuracy score of the KNeighborsClassifier() is:64.39%
-------------------------------------------------------------
the cross validation score of RandomForestClassifier(random_state=0) is =[0.85245902 0.90163934 0.81967213 0.81666667 0.8       ]
the accuracy score of the RandomForestClassifier(random_state=0) is:83.81%
-------------------------------------------------------------

**Inference**:The linear regression has the highset accuracy score & the kNeighborclassifier has the lowest accuracy score

### Comparing the model with different hyperparameter using GridSearchCV

In [17]:
#list of models
model_list=[LogisticRegression(max_iter=10000),SVC(), KNeighborsClassifier(),RandomForestClassifier(random_state=0)]

In [18]:
#creating the dictonary containing all the values for above mention models 
model_hyperparameter={
    'log_reg_hyperparameters':{
    'C':[1,5,10,20]
    
    },
    'svc_hyperparameters':{
        'kernel':['linear','poly','rbf','sigmoid'],'C':[1,5,10,20]
    },
    'KNN_hyperparameter':{
        'n_neighbors':[3,5,10]
    },
    'random_forest_hyperparameters':{
        
        'n_estimators':[10,20,50,100]
    }
    
}

In [19]:
#lets check the type 
type(model_hyperparameter)

dict

In [21]:
#let's print the values of the dict
print(model_hyperparameter.values())

dict_values([{'C': [1, 5, 10, 20]}, {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}, {'n_neighbors': [3, 5, 10]}, {'n_estimators': [10, 20, 50, 100]}])

In [25]:
model_hyperparameter['log_reg_hyperparameters']

{'C': [1, 5, 10, 20]}

In [23]:
#instead we are gonna store the index in model_keys and acess with the help of indexes 
model_keys=list(model_hyperparameter.keys())
print(model_keys)

['log_reg_hyperparameters', 'svc_hyperparameters', 'KNN_hyperparameter', 'random_forest_hyperparameters']

In [24]:
#let's see how we are gonna accress the values of our dict
model_hyperparameter[model_keys[0]]

{'C': [1, 5, 10, 20]}

In [26]:
#so i can access any hyperparameter using the index

## Applying the GridSreachCV

In [60]:
 def ModelSelection(list_of_models,hyperparameter_dict):
     result=[]
     i=0
     for model in list_of_models:
             key=model_keys[i]
             params=hyperparameter_dict[key]
             i+=1
             print(model)
             print(params)
             print('---------------------------------------------------')
        #appyling the girdsearchcv
             classifier=GridSearchCV(model,params,cv=5)
             #fitting the data
             classifier.fit(X,Y)
             result.append({
                 'model used':model,
                 'highest score':classifier.best_score_*100,
                 'best hyperparameter':classifier.best_params_
             })
     result_dataframe=pd.DataFrame(result,columns=['model used','highest score','best hyperparameter'])
     return result_dataframe

In [61]:
ModelSelection(model_list,model_hyperparameter)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}
---------------------------------------------------
SVC()
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
---------------------------------------------------
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
---------------------------------------------------
RandomForestClassifier(random_state=0)
{'n_estimators': [10, 20, 50, 100]}
---------------------------------------------------

,model used,highest score,best hyperparameter
0,LogisticRegression(max_iter=10000),83.158470,{'C': 5}
1,SVC(),82.830601,"{'C': 1, 'kernel': 'linear'}"
2,KNeighborsClassifier(),64.387978,{'n_neighbors': 5}
3,RandomForestClassifier(random_state=0),83.808743,{'n_estimators': 100}

**RandomForestClassifier with n_estimators:100 has the highest accuracy among all the models**